global using Domain.Entities;
global using MediatR;
global using AutoMapper;
global using Domain.Entities;
global using Domain.Events;
global using Domain.Enums;
global using Application.Common.Validators;
global using Application.Common.Exceptions;
global using Application.Common.Interfaces;